
[web_masked_st]
DATETIME_CONFIG = NONE
LINE_BREAKER = ([\r\n]+)
category = Custom
pulldown_type = 1
TRANSFORMS-mask-user = mask_username
TRANSFORMS-mask-ip = mask_client_ip
TRANSFORMS-mask-session = mask_sessionid

[web_raw1]
DATETIME_CONFIG = 
LINE_BREAKER = ([\r\n]+)
category = Custom
pulldown_type = 1

[exfil_http_raw]
DATETIME_CONFIG = 
LINE_BREAKER = ([\r\n]+)
category = Custom
pulldown_type = 1

[exfil_http_masked]
DATETIME_CONFIG = 
LINE_BREAKER = ([\r\n]+)
category = Custom
pulldown_type = 1

[lateral_raw_st]
DATETIME_CONFIG = NONE
LINE_BREAKER = ([\r\n]+)
category = Custom
pulldown_type = 1
TRANSFORMS-maskuser = mask_lm_user
TRANSFORMS-maskip = mask_lm_ip
TRANSFORMS-masktarget = mask_lm_target

[lateral_masked_st]
DATETIME_CONFIG = NONE
LINE_BREAKER = ([\r\n]+)
category = Custom
pulldown_type = 1

