[mask_username]
REGEX = (?i)(.*username=)[^\s]+(.*)
FORMAT = $1MASKED_USER$2
DEST_KEY = _raw

[mask_client_ip]
REGEX = (?i)(.*client_ip=)\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(.*)
FORMAT = $1MASKED_IP$2
DEST_KEY = _raw

[mask_sessionid]
REGEX = (?i)(.*sessionid=)[^\s]+(.*)
FORMAT = $1MASKED_SESSION$2
DEST_KEY = _raw




[mask_lm_user]
REGEX = (.*)username=[^\s]+(.*)
FORMAT = $1username=MASKED_USER$2
DEST_KEY = _raw

[mask_lm_ip]
REGEX = (.*)client_ip=[^\s]+(.*)
FORMAT = $1client_ip=MASKED_IP$2
DEST_KEY = _raw

[mask_lm_target]
REGEX = (.*)target_host=[^\s]+(.*)
FORMAT = $1target_host=MASKED_TARGET$2
DEST_KEY = _raw